import './globals.css';
import type { Metadata } from 'next';
import NavBar from './components/navbar/NavBar';

export const metadata: Metadata = {
  title: 'Book Store App',
  description: 'Generated by create next app',
};

interface Props {
  children: React.ReactNode;
}
const RootLayout = ({ children }: Props) => {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
};
export default RootLayout;
